# Site settings
baseurl: "" # edit baseurl to simply '/' if using as your personal page (instead of a project page)
url: # the base hostname & protocol for your site, e.g. http://example.com
lang: 'ca'
google_analytics:

# Site info
title: Arcadia escola autogestionària
mobile_title: Arcadia
description: "Arcadia es un proyecto de centro educativo autogestionario, cooperativo y comunitario en Barcelona."
license: "Continguts sota llicencia CC Reconeixement - NoComercial - CompartirIgual 4.0"
color: #b80000

# Owner's info
author: 'Escola Arcàdia'
location: 'Carrer de la Constitució 25, 08014 Barcelona'
email: info@adabits.org
tel: '934 321 765'
logo: logo-dark.png
twitter: adab1ts

# Where things are
source: src
destination:
images_path: assets/img
theme_scripts_path: assets/pillar/js
theme_styles_path: assets/pillar/css
theme_fonts_path: assets/pillar/fonts

# Collections
collections:
  - contacte
  - escola
  - funcionament
  - home
  - image-blocks
  - objectius
  - pedagogia
  - pilars
  - projecte
  - testimonials
  - teoria
  - vertical-cards

# Handling Reading
encoding: "utf-8"
markdown_ext: "md"

# Conversion
markdown: kramdown
highlighter: rouge

# Build settings
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

# Outputting
permalink: pretty
timezone: Europe/Madrid
