# Site settings
title: Arcadia escola autogestionària
mobile_title: Arcadia
description: "Arcadia es un proyecto de centro educativo autogestionario, cooperativo y comunitario en Barcelona."
author: "Escola Arcàdia"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
email: your-email@domain.com
lang: ca
google_analytics:
logo:
location: "Carrer de la Constitució 25, 08014 Barcelona"
twitter_username: jekyllrb
license: "Continguts sota llicencia CC Reconeixement - NoComercial - CompartirIgual 4.0"

# Where things are
source:
destination:
images_path: assets/img
scripts_path: assets/js
styles_path: assets/css

# Collections
collections:
  - contacte
  - escola
  - funcionament
  - home
  - image-blocks
  - objectius
  - pedagogia
  - pilars
  - projecte
  - testimonials
  - teoria
  - vertical-cards

# Handling Reading
encoding: "utf-8"
markdown_ext: "md"

# Conversion
markdown: kramdown
highlighter: rouge

# Build settings
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

# Outputting
permalink: pretty
timezone: Europe/Madrid
